### ISSUE TITLE
xontrib-direnv uses an incorrect commit

### ISSUE THREAD

**Issue by SamLukeYes** [drmikecrowe/nur-packages#4]
The `xontrib-direnv` package in this repo claims to be the latest version 1.6.3, but is actually using an outdated commit https://github.com/74th/xonsh-direnv/commit/3bea5847b9459c5799c64966ec85e624d0be69b9.

**Comment by drmikecrowe** [comment]
Fixed via [63d1081](https://github.com/drmikecrowe/nur-packages/commit/63d1081ba51e78401979d6b1abbfaa1315657de9)
