### ISSUE TITLE
Add `xonsh` and `xontrib` topics to the repository about

### ISSUE THREAD

**Issue by anki-code** [drmikecrowe/nur-packages#6]
To add this repo to https://github.com/topics/xontrib

It's here:
<img width="337" alt="image" src="https://github.com/user-attachments/assets/b101b94b-5c3a-41c8-868a-d942eb987cf6">
<img width="219" alt="image" src="https://github.com/user-attachments/assets/cf6460da-e124-48ad-b0ec-60e54c0a5ed4">

Please add short description also.

May be it's good to add `xonsh`, `xontrib`, `xonsh-nix` topic as well.

**Comment by drmikecrowe** [comment]
Thanks @anki-code -- good suggestion
